### ISSUE TITLE
Calendar week day display is incorrect

### ISSUE THREAD

**Issue by asapovk** [pt-one/StageUI#2]
<img width="1423" alt="Снимок экрана 2021-02-11 в 11 45 09" src="https://user-images.githubusercontent.com/17439500/107617064-437f2b80-6c60-11eb-86f6-3d9dfa4fd6a1.png">

**Comment by itrcz** [comment]
[itrcz@560af46](https://github.com/pt-one/StageUI/commit/74db639584340c6cbfaca9299f8f6360cde48dae)
